INSERT INTO PASSENGER VALUES ('Sejal','AC','F','Bengaluru','Chennai',350,'Sleeper');
INSERT INTO PASSENGER VALUES ('Anmol','Non-AC','M','Mumbai','Hyderabad',700,'Sitting');
INSERT INTO PASSENGER VALUES ('Pallavi','AC','F','Panaji','Bengaluru',600,'Sleeper');
INSERT INTO PASSENGER VALUES ('Khusboo','AC','F','Chennai','Mumbai',1500,'Sleeper');
INSERT INTO PASSENGER VALUES ('Udit','Non-AC','M','Trivandrum','panaji',1000,'Sleeper');
INSERT INTO PASSENGER VALUES ('Ankur','AC','M','Nagpur','Hyderabad',500,'Sitting');
INSERT INTO PASSENGER VALUES ('Hemant','Non-AC','M','panaji','Mumbai',700,'Sleeper');
INSERT INTO PASSENGER VALUES ('Manish','Non-AC','M','Hyderabad','Bengaluru',500,'Sitting');
INSERT INTO PASSENGER VALUES ('Piyush','AC','M','Pune','Nagpur',700,'Sitting');



INSERT INTO PRICE VALUES ('Sleeper',350,770);
INSERT INTO PRICE VALUES ('Sleeper',500,1100);
INSERT INTO PRICE VALUES ('Sleeper',600,1320);
INSERT INTO PRICE VALUES ('Sleeper',700,1540);
INSERT INTO PRICE VALUES ('Sleeper',1000,2200);
INSERT INTO PRICE VALUES ('Sleeper',1200,2640);
INSERT INTO PRICE VALUES ('Sleeper',350,434);
INSERT INTO PRICE VALUES ('Sitting',500,620);
INSERT INTO PRICE VALUES ('Sitting',500,620);
INSERT INTO PRICE VALUES ('Sitting',600,744);
INSERT INTO PRICE VALUES ('Sitting',700,868);
INSERT INTO PRICE VALUES ('Sitting',1000,1240);
INSERT INTO PRICE VALUES ('Sitting',1200,1488);
INSERT INTO PRICE VALUES ('Sitting',1500,1860);

COMMIT;

